image: python:3.11-alpine

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Собираем проект..."
    - mkdir build

test_job:
  stage: test
  script:
    - echo "Запускаем тесты..."

deploy_job:
  stage: deploy
  script:
    - echo "Разворачиваем проект на сервер..."