import os
from datetime import datetime, timedelta
from airflow.decorators import dag, task
from airflow.providers.amazon.aws.sensors.s3 import S3KeySensor
from airflow.providers.docker.operators.docker import DockerOperator
from airflow.providers.yandex.operators.dataproc import (
    DataprocCreateClusterOperator,
    DataprocCreatePysparkJobOperator,
    DataprocDeleteClusterOperator,
)
from airflow.operators.empty import EmptyOperator


def send_telegram_alert(context):
    import requests
    import logging

    ti = context["task_instance"]
    dag_id, task_id, log_url = ti.dag_id, ti.task_id, ti.log_url
    execution_date = context["logical_date"].strftime("%Y-%m-%d %H:%M")

    message = (
        f"🚨 *Airflow Alert: Task Failed*\n\n"
        f"📅 *Date:* `{execution_date}`\n"
        f"🗂 *DAG:* `{dag_id}`\n"
        f"⚡️ *Task:* `{task_id}`\n\n"
        f"🔗 [Open logs in Airflow UI]({log_url})"
    )

    token = os.environ.get("TG_BOT_TOKEN", "")
    url = f"https://api.telegram.org/bot{token}/sendMessage"

    payload = {
        "chat_id": os.environ.get("TG_CHAT_ID"),
        "text": message,
        "parse_mode": "Markdown",
    }
    try:
        response = requests.post(url, json=payload, timeout=10)
        response.raise_for_status()
    except Exception as e:
        logging.exception("Couldn't send notification to Telegram")


@task(task_id="fetch_spark_metrics", trigger_rule="all_done")
def fetch_spark_metrics(configs, ds=None, ti=None, dag_run=None):
    import json
    import logging
    from airflow.providers.amazon.aws.hooks.s3 import S3Hook
    from airflow.exceptions import AirflowFailException

    logger = logging.getLogger(__name__)

    cfg = configs["cfg"]
    bucket_name = cfg["s3"]["silver"]
    metrics_path = cfg["infrastructure"]["metrics_path"]
    aws_conn_id = cfg["airflow"]["aws_conn_id"]
    prefix = f"{metrics_path}/{ds}/"

    s3_hook = S3Hook(aws_conn_id=aws_conn_id)

    logger.info(
        f"Looking for metrics in bucket '{bucket_name}' with prefix '{prefix}'..."
    )
    keys = s3_hook.list_keys(bucket_name=bucket_name, prefix=prefix)

    if not keys:
        raise FileNotFoundError(
            f"Metrics for the {ds} date were not found in the {bucket_name} bucket along the {prefix} path"
        )

    json_keys = [
        k for k in keys if k.endswith(".json") and not k.split("/")[-1].startswith("_")
    ]

    if not json_keys:
        raise FileNotFoundError(
            f"The .json file generated by Spark is missing in the {prefix} folder"
        )

    target_key = json_keys[0]
    logger.info(f"Reading metrics file: {target_key}")

    file_content = s3_hook.read_key(key=target_key, bucket_name=bucket_name)
    metrics_data = json.loads(file_content)

    logger.info("=" * 50)
    logger.info(f"📊 DATA QUALITY METRICS FOR DATASET DATE: {ds}")
    logger.info(f"Total Rows Processed : {metrics_data.get('total_rows', 0)}")
    logger.info(f"Valid Rows (Clean)   : {metrics_data.get('valid_rows', 0)}")
    logger.info(f"Invalid Rows (Dirty) : {metrics_data.get('invalid_rows', 0)}")
    logger.info(f"Error Rate           : {metrics_data.get('error_percent', 0.0)}%")
    logger.info("=" * 50)

    if dag_run:
        bronze_to_silver_ti = dag_run.get_task_instance("bronze_to_silver")

        if bronze_to_silver_ti and bronze_to_silver_ti.state == "failed":
            raise AirflowFailException(
                f"The pipeline was interrupted at the bronze_to_silver step due to data quality issues! "
                f"A critical percentage of errors has been recorded: {metrics_data.get('error_percent', 0.0)}%"
            )

    return metrics_data


@task
def fetch_config_from_s3():
    import yaml

    env = os.getenv("SPARK_ENV", "dev")

    config_path = f"/opt/airflow/config/{env}_config.yaml"
    with open(config_path, "r") as f:
        cfg = yaml.safe_load(f)

    schema_path = f"/opt/airflow/config/schemas.yaml"
    with open(schema_path, "r") as f:
        schema = yaml.safe_load(f)

    return {"cfg": cfg, "schema": schema}


@task
def archiving_raw(configs_dict: dict, ds=None):
    import logging
    from airflow.providers.amazon.aws.hooks.s3 import S3Hook

    cfg = configs_dict["cfg"]
    aws_conn_id = cfg["airflow"]["aws_conn_id"]

    source_bucket = cfg["s3"]["visits_json"]["bucket"]
    source_prefix = f"{cfg['s3']['visits_json']['path']}{ds}/"

    target_bucket = cfg["s3"]["visits_archive"]["bucket"]
    target_prefix = f"{cfg['s3']['visits_archive']['path']}{ds}/"

    logging.info(
        f"Archiving {source_bucket}/{source_prefix} to {target_bucket}/{target_prefix}"
    )

    s3_hook = S3Hook(aws_conn_id=aws_conn_id)
    keys = s3_hook.list_keys(bucket_name=source_bucket, prefix=source_prefix)

    if not keys:
        logging.info(
            f"In the folder {source_prefix} no files were found for archiving."
        )
        return

    file_count = 0
    for source_key in keys:
        if source_key.endswith("/"):
            continue

        filename = source_key.replace(source_prefix, "")
        target_key = f"{target_prefix}{filename}"

        s3_hook.copy_object(
            source_bucket_key=source_key,
            dest_bucket_key=target_key,
            source_bucket_name=source_bucket,
            dest_bucket_name=target_bucket,
        )
        file_count += 1

    if keys:
        s3_hook.delete_objects(bucket_name=source_bucket, keys=keys)
        logging.info(f"Successfully deleted {len(keys)} source files from S3.")

    logging.info(f"Archiving is complete. Moved files: {file_count}")

default_args = {
    "owner": "data_engineers",
    "depends_on_past": True,
    "email_on_failure": False,
    "retries": 2,
    "retry_delay": timedelta(minutes=5),
    "on_failure_callback": send_telegram_alert,
}


@dag(
    dag_id="dwh_core_elthub",
    default_args=default_args,
    description="Medical Visit Processing Pipeline: Bronze -> Silver -> Gold -> ClickHouse",
    render_template_as_native_obj=True,
    schedule_interval="0 2 * * *",
    start_date=datetime(2026, 1, 1),
    catchup=True,
    max_active_runs=1,
    tags=["dwh", "medanalytics", "iceberg", "clickhouse"],
)
def dwh_core_elthub():
    configs = fetch_config_from_s3()

    wait_for_bronze_data = S3KeySensor(
        task_id="wait_for_bronze_data",
        bucket_name="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['s3']['bronze'] }}",
        bucket_key="visits/{{ ds }}/*",
        wildcard=True,
        aws_conn_id="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['airflow']['aws_conn_id'] }}",
        mode="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['airflow']['sensor']['mode'] }}",
        poke_interval="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['airflow']['sensor']['poke_interval'] | int }}",
        timeout="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['airflow']['sensor']['timeout'] | int }}",
        soft_fail="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['airflow']['sensor']['soft_fail'] | string | lower == 'true' }}",
    )

    create_cluster = DataprocCreateClusterOperator(
        task_id="create_cluster",
        yc_conn_id="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['airflow']['yc_conn_id'] }}",
        cluster_name="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['cluster_name'] }}-{{ ds }}",
        zone="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['dataproc']['zone'] }}",
        subnet_id="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['dataproc']['subnet_id'] }}",
        service_account_id="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['dataproc']['service_account_id'] }}",
        masternode_resource_preset="s3-c{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['dataproc']['master_cores'] }}-m{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['dataproc']['master_memory'] }}",
        masternode_disk_type="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['dataproc']['disk_type_id_master'] }}",
        masternode_disk_size="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['dataproc']['disk_size_master'] | int }}",
        computenode_resource_preset="s3-c{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['dataproc']['worker_cores'] }}-m{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['dataproc']['worker_memory'] }}",
        computenode_disk_type="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['dataproc']['disk_type_id_worker'] }}",
        computenode_disk_size="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['dataproc']['disk_size_worker'] | int }}",
        computenode_count="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['dataproc']['worker_count'] | int }}",
    )

    ice_schema_migration = DataprocCreatePysparkJobOperator(
        task_id="iceberg_schema_migration",
        yc_conn_id="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['airflow']['yc_conn_id'] }}",
        cluster_id=create_cluster.output,
        name="{{ task.task_id }}",
        main_python_file_uri="s3a://{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['code_bucket'] }}/{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['scripts']['schema_sync_ice'] }}",
        py_files=[
            "s3a://{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['code_bucket'] }}/{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['whl_file'] }}",
            "s3a://{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['code_bucket'] }}/{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['dependencies'] }}",
        ],
        properties="""{% set c = ti.xcom_pull(task_ids='fetch_config_from_s3') %}
            {% set cat = c['schema']['databases']['silver']['catalog'] %}
            {{
                {
                    'spark.sql.catalog.' ~ cat: 'org.apache.iceberg.spark.SparkCatalog',
                    'spark.sql.catalog.' ~ cat ~ '.type': 'hadoop',
                    'spark.sql.catalog.' ~ cat ~ '.warehouse': 's3a://' ~ c['cfg']['s3']['silver_warehouse']['bucket'] ~ '/' ~ c['cfg']['s3']['silver_warehouse']['path'],
                    'spark.sql.catalog.' ~ cat ~ '.io-impl': 'org.apache.iceberg.aws.s3.S3FileIO',
                    'spark.sql.catalog.' ~ cat ~ '.s3.endpoint': c['cfg']['s3']['storage'],
                    'spark.sql.catalog.' ~ cat ~ '.s3.path-style-access': 'true',
                    'spark.sql.catalog.' ~ cat ~ '.aws.credentials.provider': 'org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider',
                    'spark.sql.extensions': 'org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions',
                    'spark.sql.logLevel': c['cfg']['log_level']['spark_sql']
                }
            }}""",
        packages="""{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['packages'].split(',') | map('trim') | list }}""",
        repositories=["{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['repositories'] }}"],
        args=[
            "--config_json",
            "{{ ti.xcom_pull(task_ids='fetch_config_from_s3') | tojson }}",
        ],
    )

    load_ref_data = DataprocCreatePysparkJobOperator(
        task_id="load_ref_data",
        yc_conn_id="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['airflow']['yc_conn_id'] }}",
        cluster_id=create_cluster.output,
        name="{{ task.task_id }}",
        main_python_file_uri="s3a://{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['code_bucket'] }}/{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['scripts']['load_ref_data'] }}",
        py_files=[
            "s3a://{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['code_bucket'] }}/{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['whl_file'] }}",
            "s3a://{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['code_bucket'] }}/{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['dependencies'] }}",
        ],
        properties="""{% set c = ti.xcom_pull(task_ids='fetch_config_from_s3') %}
            {% set cat = c['schema']['databases']['silver']['catalog'] %}
            {{
                {
                    'spark.sql.catalog.' ~ cat: 'org.apache.iceberg.spark.SparkCatalog',
                    'spark.sql.catalog.' ~ cat ~ '.type': 'hadoop',
                    'spark.sql.catalog.' ~ cat ~ '.warehouse': 's3a://' ~ c['cfg']['s3']['silver_warehouse']['bucket'] ~ '/' ~ c['cfg']['s3']['silver_warehouse']['path'],
                    'spark.sql.catalog.' ~ cat ~ '.io-impl': 'org.apache.iceberg.aws.s3.S3FileIO',
                    'spark.sql.catalog.' ~ cat ~ '.s3.endpoint': c['cfg']['s3']['storage'],
                    'spark.sql.catalog.' ~ cat ~ '.s3.path-style-access': 'true',
                    'spark.sql.catalog.' ~ cat ~ '.aws.credentials.provider': 'org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider',
                    'spark.sql.extensions': 'org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions',
                    'spark.sql.logLevel': c['cfg']['log_level']['spark_sql']
                }
            }}""",
        packages="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['packages'].split(',') | map('trim') | list }}",
        repositories=["{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['repositories'] }}"],
        args=[
            "--config_json",
            "{{ ti.xcom_pull(task_ids='fetch_config_from_s3') | tojson }}",
        ],
    )

    bronze_to_silver = DataprocCreatePysparkJobOperator(
        task_id="bronze_to_silver",
        yc_conn_id="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['airflow']['yc_conn_id'] }}",
        cluster_id=create_cluster.output,
        name="{{ task.task_id }}",
        main_python_file_uri="s3a://{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['code_bucket'] }}/{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['scripts']['bronze_to_silver'] }}",
        py_files=[
            "s3a://{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['code_bucket'] }}/{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['whl_file'] }}",
            "s3a://{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['code_bucket'] }}/{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['dependencies'] }}",
        ],
        properties="""{% set c = ti.xcom_pull(task_ids='fetch_config_from_s3') %}
            {% set cat = c['schema']['databases']['silver']['catalog'] %}
            {{
                {
                    'spark.sql.catalog.' ~ cat: 'org.apache.iceberg.spark.SparkCatalog',
                    'spark.sql.catalog.' ~ cat ~ '.type': 'hadoop',
                    'spark.sql.catalog.' ~ cat ~ '.warehouse': 's3a://' ~ c['cfg']['s3']['silver_warehouse']['bucket'] ~ '/' ~ c['cfg']['s3']['silver_warehouse']['path'],
                    'spark.sql.catalog.' ~ cat ~ '.io-impl': 'org.apache.iceberg.aws.s3.S3FileIO',
                    'spark.sql.catalog.' ~ cat ~ '.s3.endpoint': c['cfg']['s3']['storage'],
                    'spark.sql.catalog.' ~ cat ~ '.s3.path-style-access': 'true',
                    'spark.sql.catalog.' ~ cat ~ '.aws.credentials.provider': 'org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider',
                    'spark.sql.extensions': 'org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions',
                    'spark.sql.logLevel': c['cfg']['log_level']['spark_sql']
                }
            }}""",
        packages="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['packages'].split(',') | map('trim') | list }}",
        repositories=["{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['repositories'] }}"],
        args=[
            "--config_json",
            "{{ ti.xcom_pull(task_ids='fetch_config_from_s3') | combine({'ds': ds}) | tojson }}",
        ],
    )

    fetch_metrics_task = fetch_spark_metrics(configs=configs)

    silver_to_gold = DataprocCreatePysparkJobOperator(
        task_id="silver_to_gold",
        yc_conn_id="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['airflow']['yc_conn_id'] }}",
        cluster_id=create_cluster.output,
        name="{{ task.task_id }}",
        main_python_file_uri="s3a://{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['code_bucket'] }}/{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['scripts']['silver_to_gold'] }}",
        py_files=[
            "s3a://{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['code_bucket'] }}/{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['whl_file'] }}",
            "s3a://{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['code_bucket'] }}/{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['infrastructure']['dependencies'] }}",
        ],
        properties="""{% set c = ti.xcom_pull(task_ids='fetch_config_from_s3') %}
            {% set cat = c['schema']['databases']['gold']['catalog'] %}
            {{
                {
                    'spark.sql.catalog.' ~ cat: 'org.apache.iceberg.spark.SparkCatalog',
                    'spark.sql.catalog.' ~ cat ~ '.type': 'hadoop',
                    'spark.sql.catalog.' ~ cat ~ '.warehouse': 's3a://' ~ c['cfg']['s3']['gold_warehouse']['bucket'] ~ '/' ~ c['cfg']['s3']['gold_warehouse']['path'],
                    'spark.sql.catalog.' ~ cat ~ '.io-impl': 'org.apache.iceberg.aws.s3.S3FileIO',
                    'spark.sql.catalog.' ~ cat ~ '.s3.endpoint': c['cfg']['s3']['storage'],
                    'spark.sql.catalog.' ~ cat ~ '.s3.path-style-access': 'true',
                    'spark.sql.catalog.' ~ cat ~ '.aws.credentials.provider': 'org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider',
                    'spark.sql.extensions': 'org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions',
                    'spark.sql.logLevel': c['cfg']['log_level']['spark_sql']
                }
            }}""",
        packages="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['packages'].split(',') | map('trim') | list }}",
        repositories=["{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['repositories'] }}"],
        args=[
            "--config_json",
            "{{ ti.xcom_pull(task_ids='fetch_config_from_s3') | tojson }}",
        ],
    )

    archive_raw = archiving_raw(configs_dict=configs)

    dbt_clickhouse = DockerOperator(
        task_id="dbt_clickhouse",
        image="dbt-worker:latest",
        api_version="auto",
        auto_remove=True,
        command="dbt build --profiles-dir . --target base",
        environment={
            "STORAGE": os.environ.get("STORAGE"),
            "GOLD": os.environ.get("GOLD"),
            "ICE_ACCESS_KEY_ID": os.environ.get("ICE_ACCESS_KEY_ID"),
            "ICE_SECRET_ACCESS_KEY": os.environ.get("ICE_SECRET_ACCESS_KEY"),
            "CLICKHOUSE_HOST": os.environ.get("CLICKHOUSE_HOST"),
            "CLICKHOUSE_PORT": os.environ.get("CLICKHOUSE_PORT"),
            "CLICKHOUSE_USER": os.environ.get("CLICKHOUSE_USER"),
            "CLICKHOUSE_PASSWORD": os.environ.get("CLICKHOUSE_PASSWORD"),
            "CLICKHOUSE_DATABASE": os.environ.get("CLICKHOUSE_DATABASE"),
        },
        docker_url="unix://var/run/docker.sock",
        network_mode="host",
    )

    join_computations = EmptyOperator(
        task_id="join_computations"
    )

    delete_cluster = DataprocDeleteClusterOperator(
        task_id="delete_cluster",
        trigger_rule="all_done",
        yc_conn_id="{{ ti.xcom_pull(task_ids='fetch_config_from_s3')['cfg']['airflow']['yc_conn_id'] }}",
        cluster_id=create_cluster.output,
    )

    (
        configs
        >> wait_for_bronze_data
        >> create_cluster
        >> ice_schema_migration
        >> load_ref_data
        >> bronze_to_silver
        >> fetch_metrics_task
    )
    fetch_metrics_task >> silver_to_gold >> dbt_clickhouse
    fetch_metrics_task >> archive_raw
    [dbt_clickhouse, archive_raw] >> join_computations
    [create_cluster, join_computations] >> delete_cluster


dwh_core_elthub_dag = dwh_core_elthub()
