name: prod push

on:
  push:
    branches: [ main ]
    
jobs:
  build-and-upload:
    runs-on: ubuntu-24.04
    env:
      SPARK_ENV: prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse CODE_BUCKET from config
        id: parse_config
        run: |
          ENV_LOWER=$(echo "${{ env.SPARK_ENV }}" | tr '[:upper:]' '[:lower:]')
          CONFIG_FILE="config/${ENV_LOWER}_config.yaml"

          echo "CODE_BUCKET=$(yq eval '.infrastructure.code_bucket' $CONFIG_FILE)" >> $GITHUB_ENV
          echo "STORAGE=$(yq eval '.s3.storage' $CONFIG_FILE)" >> $GITHUB_ENV
          echo "DEPARTMENTS_BUCKET=$(yq eval '.s3.departments_csv.bucket' $CONFIG_FILE)" >> $GITHUB_ENV
          echo "PROFESSIONS_BUCKET=$(yq eval '.s3.professions_csv.bucket' $CONFIG_FILE)" >> $GITHUB_ENV
          echo "ENV_LOWER=$ENV_LOWER" >> $GITHUB_ENV

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Build Wheel package
        run: uv build --wheel

      - name: Configure AWS Credentials (Yandex S3)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.YC_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.YC_AWS_SECRET_ACCESS_KEY }}
          aws-region: ru-central1

      - name: Build and upload dependencies.zip
        run: |
          uv pip compile pyproject.toml -o requirements.txt
          grep -E -v "pyspark|py4j|# " requirements.txt > requirements-cloud.txt
          
          rm -rf dist/dependencies dist/unpacked_libs
          mkdir -p dist/dependencies dist/unpacked_libs
          
          uv pip download -r requirements-cloud.txt \
            --python-version 3.8 \
            --platform manylinux2014_x86_64 \
            -d dist/dependencies/
          
          for whl in dist/dependencies/*.whl; do 
            unzip -q "$whl" -d dist/unpacked_libs/
          done
          
          (cd dist/unpacked_libs && zip -q -r ../dependencies.zip .)
          
          aws --endpoint-url=${{ env.STORAGE }} s3 cp dist/dependencies.zip s3://${{ env.CODE_BUCKET }}/dependencies.zip

      - name: Upload artifacts to Yandex Storage (S3)
        run: |
          aws --endpoint-url=${{ env.STORAGE }} s3 cp dist/ s3://${{ env.CODE_BUCKET }}/ --recursive --exclude "*/*" --include "*.whl"
          aws --endpoint-url=${{ env.STORAGE }} s3 cp jobs/ s3://${{ env.CODE_BUCKET }}/jobs/ --recursive
          aws --endpoint-url=${{ env.STORAGE }} s3 cp config/${{ env.ENV_LOWER }}_config.yaml s3://${{ env.CODE_BUCKET }}/
          aws --endpoint-url=${{ env.STORAGE }} s3 cp config/schemas.yaml s3://${{ env.CODE_BUCKET }}/schemas.yaml
          aws --endpoint-url=${{ env.STORAGE }} s3 cp data/departments.csv s3://${{ env.DEPARTMENTS_BUCKET }}/departments.csv
          aws --endpoint-url=${{ env.STORAGE }} s3 cp data/professions.csv s3://${{ env.PROFESSIONS_BUCKET }}/professions.csv
  
  deploy-to-vm:
    needs: build-and-upload 
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy and Build Image via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "/home/${{ secrets.PROD_SERVER_USER }}/sparkmedanalytics" ]; then
              mkdir -p /home/${{ secrets.PROD_SERVER_USER }}/sparkmedanalytics
              cd /home/${{ secrets.PROD_SERVER_USER }}/sparkmedanalytics
              git clone https://github.com/${{ github.repository }}.git .
            else
              cd /home/${{ secrets.PROD_SERVER_USER }}/sparkmedanalytics
            fi
            
            git fetch origin ${{ github.ref_name }}
            DIFF=$(git diff --name-only HEAD origin/${{ github.ref_name }})

            git pull origin ${{ github.ref_name }}
            
            if [ -z "$DIFF" ] || echo "$DIFF" | grep -E "requirements-airflow.txt|dockerfile.airflow|compose\.y.*ml|config/"; then
                echo "Detected infra or config changes. Rebuilding Compose..."
                docker compose up -d --build
            fi

            if [ -z "$DIFF" ] || echo "$DIFF" | grep -E "dbt_project/|dockerfile.dbt"; then
                echo "Detected changes in dbt_project. Rebuilding dbt-worker image..."
                docker build -t dbt-worker:latest -f dockerfile.dbt .
                docker image prune -f
            fi

            if echo "$DIFF" | grep -q "dags/"; then
                echo "DAG changes detected. Airflow will sync them via volumes."
                docker compose restart airflow-scheduler
            fi